# docker version
version: '3.7'

# docker service
services:


  # php server
  php:
    build: docker
    restart: always
    volumes:
      - ./:/var/www/html/
    ports:
      - '8100:80'


  # database
  db:
    image: library/mariadb:10.11
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: super
      MYSQL_PASSWORD: pass
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    ports:
      - '6033:3306'
